export const holders = [
  {
    icons: "none",
    rounded: "lg",
    theme: 1,
    holderName: "محمد أحمد",
    holderTitle: "الرئيس التنفيذي",
    holderLocation: "القاهرة، مصر",
    holderEmail: "mohammed.ahmed@example.com",
    holderPhone: "+20-555-0101",
    color1: "red",
  },
  {
    icons: "none",
    rounded: "lg",
    theme: 0,
    holderName: "علي حسن",
    holderTitle: "المدير التقني",
    holderLocation: "دبي، الإمارات العربية المتحدة",
    holderEmail: "ali.hassan@example.com",
    holderPhone: "+971-555-0202",
    color1: "sky",
  },
  {
    icons: "line",
    rounded: "lg",
    theme: 2,
    holderName: "فاطمة يوسف",
    holderTitle: "المدير المالي",
    holderLocation: "الرياض، السعودية",
    holderEmail: "fatima.youssef@example.com",
    holderPhone: "+966-555-0303",
    color1: "black",
  },
  {
    icons: "none",
    rounded: "none",
    theme: 0,
    holderName: "عمر إبراهيم",
    holderTitle: "المدير التنفيذي للعمليات",
    holderLocation: "الدوحة، قطر",
    holderEmail: "omar.ibrahim@example.com",
    holderPhone: "+974-555-0404",
    color1: "main",
  },
  {
    icons: "none",
    rounded: "lg",
    theme: 1,
    holderName: "ليلى خالد",
    holderTitle: "المدير التسويقي",
    holderLocation: "بيروت، لبنان",
    holderEmail: "leila.khaled@example.com",
    holderPhone: "+961-555-0505",
    color1: "blue",
  },
  {
    icons: "line",
    rounded: "none",
    theme: 2,
    holderName: "يوسف عمر",
    holderTitle: "مدير الموارد البشرية",
    holderLocation: "المنامة، البحرين",
    holderEmail: "youssef.omar@example.com",
    holderPhone: "+973-555-0606",
    color1: "sky",
  },
  {
    icons: "none",
    rounded: "none",
    theme: 0,
    holderName: "سعيد علي",
    holderTitle: "مدير المبيعات",
    holderLocation: "عمان، الأردن",
    holderEmail: "saeed.ali@example.com",
    holderPhone: "+962-555-0808",
    color1: "main",
  },
  {
    icons: "none",
    rounded: "lg",
    theme: 1,
    holderName: "مريم حسن",
    holderTitle: "مديرة العمليات",
    holderLocation: "مسقط، عمان",
    holderEmail: "mariam.hassan@example.com",
    holderPhone: "+968-555-0707",
    color1: "yellow",
  },
  {
    icons: "line",
    rounded: "lg",
    theme: 1,
    holderName: "آمنة وليد",
    holderTitle: "مديرة التسويق",
    holderLocation: "الجزائر، الجزائر",
    holderEmail: "amina.waleed@example.com",
    holderPhone: "+213-555-0909",
    color1: "black",
  },
  {
    icons: "none",
    rounded: "lg",
    theme: 2,
    holderName: "سامي جابر",
    holderTitle: "مدير تكنولوجيا المعلومات",
    holderLocation: "تونس، تونس",
    holderEmail: "sami.jaber@example.com",
    holderPhone: "+216-555-1010",
    color1: "main",
  },
  {
    icons: "none",
    rounded: "none",
    theme: 2,
    holderName: "ريم حسين",
    holderTitle: "مديرة الشؤون القانونية",
    holderLocation: "طرابلس، ليبيا",
    holderEmail: "reem.hussein@example.com",
    holderPhone: "+218-555-1111",
    color1: "blue",
  },
];
